Login logout
HillelSeleniumPractice0712/ohubskaRepo pull request #2
Opened 2021-03-30 10:42 UTC by ogubskaja

https://jira.ithillel.com/browse/ONLQA0712-154
Automate tests Sprint 1

2021-03-31 17:44 UTC, britka requested changes

2021-03-31 17:44 UTC, britka commented on pom.xml
> +                <version>2.20.1</version>
Замени версию на 3.0.0-M5 , иначе будет падать

2021-03-31 17:44 UTC, britka commented on src/main/java/org/ohubska/constants/Constants.java
> +    public static final String PASSWORD = "Password12345@";
Это не должно быть в константах. Такие вещи лучше хранить в proprties файлах.
И потом вычитывать их от туда.
При том, что таких файлов может быть много для разных энвайронментов

2021-03-31 17:44 UTC, britka commented on src/test/java/org/ohubska/tests/LoginTest.java
> +        basePage= new BasePage();
Ты инициализируешь ``` basePage``` , но нигде не используешь его

2021-03-31 17:44 UTC, britka commented on src/test/java/org/ohubska/tests/LoginTest.java
> +        login = WebDriverHolder.getDriver().findElement(By.xpath("//a[@class='ico-login']"));
Это плохо, очень плохо. Зачем ты используешь тут это. 
Скрой все в нужный пэйдж обжект.

2021-03-31 17:44 UTC, britka commented on src/test/java/org/ohubska/tests/LoginTest.java
> +        loggedInPage=loginPage.successfulLogin(Constants.EMAIL,Constants.PASSWORD).waitTillPageIsLoaded();
``` Constants.EMAIL,Constants.PASSWORD ``` я зв это писал ранее

2021-03-31 17:44 UTC, britka commented on src/test/java/org/ohubska/tests/LogoutTest.java
> +        login = WebDriverHolder.getDriver().findElement(By.xpath("//a[@class='ico-login']"));
Писал ранее

2021-03-31 17:45 UTC, britka commented
При запуске через ``` mvn clean install ``` тесты падают
Почини пожалуста

2021-04-01 08:37 UTC, ogubskaja commented on pom.xml
> +                <version>2.20.1</version>
done

2021-04-01 08:38 UTC, ogubskaja commented on src/main/java/org/ohubska/constants/Constants.java
> +    public static final String PASSWORD = "Password12345@";
вынесла в переменные

2021-04-01 08:38 UTC, ogubskaja commented on src/test/java/org/ohubska/tests/LoginTest.java
> +        basePage= new BasePage();
исправила

2021-04-01 08:38 UTC, ogubskaja commented on src/test/java/org/ohubska/tests/LoginTest.java
> +        login = WebDriverHolder.getDriver().findElement(By.xpath("//a[@class='ico-login']"));
каюсь, стыдно. исправила.

2021-04-01 08:38 UTC, ogubskaja commented on src/test/java/org/ohubska/tests/LoginTest.java
> +        loggedInPage=loginPage.successfulLogin(Constants.EMAIL,Constants.PASSWORD).waitTillPageIsLoaded();
исправила

2021-04-01 08:38 UTC, ogubskaja commented on src/test/java/org/ohubska/tests/LogoutTest.java
> +        login = WebDriverHolder.getDriver().findElement(By.xpath("//a[@class='ico-login']"));
исправила

2021-04-01 08:39 UTC, ogubskaja commented
The changes have been done

2021-04-01 14:48 UTC, britka commented
Вот теперь не плохо

2021-04-01 14:48 UTC, merged